apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource-extractor.fullname" . }}
  labels:
    {{- include "resource-extractor.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "resource-extractor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "resource-extractor.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "resource-extractor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: cloudesf-configs
      initContainers:
      - name: "{{ .Chart.Name }}-init"
        image: "gcr.io/{{ .Values.image.project }}/cloudesf_init_bookstore-grpc_configs:latest"
        volumeMounts:
        - name: cloudesf-configs
          # This mount path is hardcoded in the image, do not change.
          mountPath: "/configs/inputs"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          # gcr.io/cloudesf-codelab/resourceextractor:latest
          image: "{{ .Values.image.repository }}:latest"
          volumeMounts:
          - name: cloudesf-configs
            # This mount path is hardcoded in the image, do not change.
            mountPath: "/configs/inputs"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: 3443
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
