apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "g3bookstoreserver.fullname" . }}
  labels:
    {{- include "g3bookstoreserver.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "g3bookstoreserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        sidecar.istio.io/inject: "true"
        {{- include "g3bookstoreserver.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "g3bookstoreserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: proto-descriptor
      initContainers:
      - name: "proto-descriptor-init"
        image: "gcr.io/{{ .Values.image.project }}/cloudesf_init_bookstore-grpc_configs:latest"
        volumeMounts:
        - name: proto-descriptor
          # This mount path is hardcoded in the image, do not change.
          mountPath: "/configs/inputs"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            # gcr.io/cloudesf-codelab/g3bookstoreserver:latest
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
