apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookstoreserver.fullname" . }}
  labels:
    {{- include "bookstoreserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: grpc
  selector:
    {{- include "bookstoreserver.selectorLabels" . | nindent 4 }}
