# this config create cluster role and cluster role bindings, setting up data for generating subject access review
apiVersion: v1
kind: Namespace
metadata:
  name: api-client
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-client-sa
  namespace: api-client
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-admin
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deployment-admin
subjects:
- kind: ServiceAccount
  name: api-client-sa
  namespace: api-client