# this config allow or deny all traffics correctly, using the image built from main.go
apiVersion: v1
kind: Service
metadata:
  name: extauthzserver
  labels:
    app: extauthzserver
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  - name: grpc
    port: 9000
    targetPort: 9000
  selector:
    app: extauthzserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: extauthzserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extauthzserver
  template:
    metadata:
      labels:
        app: extauthzserver
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: IfNotPresent
        name: extauthzserver
        ports:
        - containerPort: 8000
        - containerPort: 9000
# ---
# apiVersion: security.istio.io/v1beta1
# kind: AuthorizationPolicy
# metadata:
#   name: allow-certain-sa
# spec:
#   action: ALLOW
#   rules:
#   - from:
#     - source:
#         principals: ["cluster.local/ns/default/sa/sleep"]
#     to:
#     - operation:
#         methods: ["*"]
#         paths: ["*"]
# allow all - works
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-all
spec:
  rules:
  - {}

# Deny all - works
# ---
# apiVersion: security.istio.io/v1beta1
# kind: AuthorizationPolicy
# metadata:
#   name: deny-all
# spec:
#   {}