{{- range $index, $version := .Values.versions }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver-{{ $version }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpserver
      version: {{ $version | quote }}
  template:
    metadata:
      labels:
        app: httpserver
        version: {{ $version | quote }}
    spec:
      serviceAccountName: httpserver
      containers:
      - image: gcr.io/yangguan-gke-dev/http-server:yangguan
        imagePullPolicy: IfNotPresent
        name: httpserver
        command:
        - "/server"
        args:
        - "-version"
        - {{ $version | quote }}
        ports:
        - containerPort: 8000
---
{{- end }}
