apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpserver-virtual-service
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/istio-gateway
  http:
{{- range $index, $version := .Values.versions }}
  - name: http-v{{ $version }}
    match:
    - headers:
        version:
          exact: v{{ $version }}
    route:
    - destination:
        host: httpserver
        subset: v{{ $version }}
        port:
          number: 8000
{{- end}}
  - name: default
    route:
    - destination:
        host: httpserver
        port:
          number: 8000
